---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: quay.io/ansible/creator-ee:latest
    pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy