---
# Read the current content of cmdline.txt
- name: Read current cmdline.txt content
  ansible.builtin.command: cat /boot/firmware/cmdline.txt
  register: cmdline
  changed_when: false
  become: true

# Ensure cgroup parameters are present in cmdline.txt
- name: Ensure cgroup parameters are in cmdline.txt
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: true
    regexp: '^(.*?)(?:\s+cgroup_memory=1\s+cgroup_enable=memory)?$'
    line: '\1 cgroup_memory=1 cgroup_enable=memory'
    state: present
  become: true
  changed_when: "not cmdline.stdout is search('cgroup_memory=1\\s+cgroup_enable=memory$')" 