---
# Configure iscsid.conf with necessary parameters
- name: Configure iscsid.conf
  ansible.builtin.lineinfile:
    path: /etc/iscsi/iscsid.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^node.startup =', line: 'node.startup = automatic' }
    - { regexp: '^node.session.timeo.replacement_timeout =', line: 'node.session.timeo.replacement_timeout = 120' }
  become: true
  notify: restart iscsi services 