---
galaxy_info:
  author: "Ansible User"
  description: "Role for sending notifications using ntfy.sh service"
  company: ""
  license: "MIT"
  min_ansible_version: "2.9"
  
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: opensuse
      versions:
        - all
    - name: ArchLinux
      versions:
        - all
    - name: Alpine
      versions:
        - all

  galaxy_tags:
    - notification
    - ntfy
    - messaging
    - alerts
    - monitoring

dependencies: [] 