---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Get uptime before reboot
      ansible.builtin.command: uptime
      register: uptime_before
      changed_when: false
      
    - name: "Include reboot role"
      ansible.builtin.include_role:
        name: reboot
        
    - name: Get uptime after reboot
      ansible.builtin.command: uptime
      register: uptime_after
      changed_when: false