---
- name: Verify
  hosts: all
  gather_facts: true
  
  tasks:
    - name: Check if system is responsive
      ansible.builtin.command: uptime
      register: uptime_check
      changed_when: false
      
    - name: Verify system is up and running
      ansible.builtin.assert:
        that:
          - uptime_check.rc == 0
        fail_msg: "System is not responsive after reboot"
        success_msg: "System is responsive after reboot"
        
    - name: Check if systemd is running
      ansible.builtin.systemd:
        name: systemd-logind
        state: started
      register: systemd_check
      
    - name: Verify systemd service is active
      ansible.builtin.assert:
        that:
          - systemd_check.status.ActiveState == "active"
        fail_msg: "Systemd services are not running properly"
        success_msg: "Systemd services are running properly"