---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    # Mock ntfy variables for testing
    ntfy_topic: "test-topic"
    ntfy_message: "Test message from molecule"
    ntfy_server: "https://httpbin.org/post"  # Mock server for testing
    ntfy_title: "Molecule Test"
    ntfy_expected_status: [200, 201]  # httpbin.org returns 201
    ntfy_fail_on_error: false  # Don't fail on errors during testing
    ntfy_debug: true
  
  tasks:
    - name: "Include ntfy_notify role"
      ansible.builtin.include_role:
        name: ntfy_notify