---
- name: Verify
  hosts: all
  gather_facts: true
  
  tasks:
    - name: Check if ntfy_result variable exists
      ansible.builtin.assert:
        that:
          - ntfy_result is defined
        fail_msg: "ntfy_result variable should be defined after running the role"
        success_msg: "ntfy_result variable is properly defined"
        
    - name: Verify notification was processed
      ansible.builtin.debug:
        msg: "Notification processing completed successfully"
        
    - name: Test variable validation (should fail without required vars)
      block:
        - name: Include role without required variables
          ansible.builtin.include_role:
            name: ntfy_notify
          vars:
            ntfy_fail_on_error: false
            # Intentionally omit required variables
            ntfy_topic: ""
            ntfy_message: ""
      rescue:
        - name: Expected failure occurred
          ansible.builtin.debug:
            msg: "Role correctly handled missing required variables"