---
# =============================================================================
# Ansible Inventory - Kubernetes Cluster and Infrastructure
# =============================================================================
# This inventory organizes hosts by both function and platform for flexibility
# in targeting playbooks and managing configuration.
# =============================================================================

all:
  children:
    # =========================================================================
    # Kubernetes K3s Cluster
    # =========================================================================
    k3s_cluster:
      children:
        # K3s Control Plane (Master Node)
        # Single Raspberry Pi node running the K3s control plane
        k3s_control_plane:
          hosts:
            super6c_node_1:
              ansible_host: 100.116.124.84

        # K3s Worker Nodes (Agents)
        k3s_agents:
          children:
            # Raspberry Pi Worker Nodes
            pi_k3s_agents:
              hosts:
                super6c_node_2:
                  ansible_host: 100.117.19.35
                super6c_node_3:
                  ansible_host: 100.92.106.48

            # RHEL Worker Nodes
            rhel_k3s_agents:
              hosts:
                rhel_node_1:
                  ansible_host: 100.94.237.61
                rhel_node_2:
                  ansible_host: 100.71.45.39

    # =========================================================================
    # VPS / Cloud Servers
    # =========================================================================
    vps_servers:
      hosts:
        rack_nerd_1:
          ansible_host: 66.63.163.116

    # =========================================================================
    # Platform Groups (for platform-specific playbooks)
    # =========================================================================
    # All Raspberry Pi devices (useful for Raspberry Pi-specific tasks)
    all_raspberry_pi:
      children:
        k3s_control_plane:
        pi_k3s_agents:
