all:
  children:
    servers:
      children:
        kube_nodes:
          children:
            raspberrypi:
              hosts:
                super6c_node_1:
                  ansible_host: 172.16.10.246
                super6c_node_2:
                  ansible_host: 172.16.10.40
                super6c_node_3:
                  ansible_host: 172.16.10.150
            new_k3s_agents:
              hosts:
                super6c_node_4:
                  ansible_host: 172.16.10.51
                  ansible_user: root
                super6c_node_5:
                  ansible_host: 172.16.10.142
                  ansible_user: root
                super6c_node_6:
                  ansible_host: 172.16.10.140
                  ansible_user: root
      hosts:
        rack_nerd_1:
          ansible_host: 66.63.163.116
          ansible_user: root
        rhel_node_1:
          ansible_host: 100.64.52.70
