all:
  children:
    servers:
      children:
        kube-nodes:
          children:
            raspberrypi:
              hosts:
                super6c-node-1:
                  ansible_host: 172.16.10.246
                super6c-node-2:
                  ansible_host: 172.16.10.40
                super6c-node-3:
                  ansible_host: 172.16.10.150
      hosts:
        public-server-1:
          ansible_host: 66.63.163.116
        rhel-node-1:
          ansible_host: 100.64.52.70