all:
  children:
    servers:
      children:
        kube_nodes:
          children:
            raspberrypi:
              hosts:
                super6c_node_1:
                  ansible_host: 172.16.10.246
                super6c_node_2:
                  ansible_host: 172.16.10.40
                super6c_node_3:
                  ansible_host: 172.16.10.150
      hosts:
        rack_nerd_1:
          ansible_host: 66.63.163.116
          ansible_user: root
        rhel_node_1:
          ansible_host: 100.64.52.70