apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ghost
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: ghost-mysql
    app.kubernetes.io/part-of: blog
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: ansible
  annotations:
    app.kubernetes.io/description: "MySQL database service for Ghost CMS"
spec:
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: ghost-mysql
    app.kubernetes.io/component: database
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  type: ClusterIP 