apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: ghost
  labels:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/instance: ghost-blog
    app.kubernetes.io/part-of: blog
    app.kubernetes.io/component: cms
    app.kubernetes.io/managed-by: ansible
  annotations:
    app.kubernetes.io/description: "Ghost CMS service endpoint"
spec:
  selector:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/instance: ghost-blog
    app.kubernetes.io/component: cms
  ports:
  - port: 80
    targetPort: 2368
    protocol: TCP
  type: ClusterIP 