global:
  enabled: true
  tlsDisable: false
server:
  extraEnvironmentVars:
    OPENBAO_CACERT: /openbao/userconfig/openbao-server-tls/openbao.ca
    OPENBAO_TLSCERT: /openbao/userconfig/openbao-server-tls/openbao.crt
    OPENBAO_TLSKEY: /openbao/userconfig/openbao-server-tls/openbao.key

  volumes:
    - name: userconfig-openbao-server-tls
      secret:
        defaultMode: 420
        secretName: openbao-server-tls # Matches the ${SECRET_NAME} from above

  volumeMounts:
    - mountPath: /openbao/userconfig/openbao-server-tls
      name: userconfig-openbao-server-tls
      readOnly: true

  standalone:
    enabled: true
    config: |
      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/openbao/userconfig/openbao-server-tls/openbao.crt"
        tls_key_file  = "/openbao/userconfig/openbao-server-tls/openbao.key"
        tls_client_ca_file = "/openbao/userconfig/openbao-server-tls/openbao.ca"
      }

      storage "file" {
        path = "/openbao/data"
      }

      ui = true
