---
apiVersion: v1
kind: Service
metadata:
  name: openbao-loadbalancer
  namespace: vault
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: openbao
    app.kubernetes.io/name: openbao
    component: server
  ports:
  - port: 8200
    targetPort: 8200
    name: https