---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    # Override auto_reboot to prevent actual reboots during testing
    auto_reboot: false
    # Use test-specific log file
    update_log_file: /tmp/ansible-updates-test.log
  
  tasks:
    - name: "Include system_update role"
      ansible.builtin.include_role:
        name: system_update