---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance-ubuntu
    image: quay.io/ansible/creator-ee:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    groups:
      - debian_family
  - name: instance-centos
    image: quay.io/ansible/creator-ee:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    groups:
      - redhat_family

provisioner:
  name: ansible
  inventory:
    group_vars:
      debian_family:
        ansible_os_family: Debian
      redhat_family:
        ansible_os_family: RedHat

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy