---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Check if update log file was created
      ansible.builtin.stat:
        path: /tmp/ansible-updates-test.log
      register: log_file_stat
      
    - name: Verify log file exists
      ansible.builtin.assert:
        that:
          - log_file_stat.stat.exists
        fail_msg: "Update log file was not created"
        success_msg: "Update log file was successfully created"
        
    - name: Check log file content
      ansible.builtin.slurp:
        path: /tmp/ansible-updates-test.log
      register: log_content
      
    - name: Verify log contains update timestamp
      ansible.builtin.assert:
        that:
          - "'System packages updated via Ansible' in (log_content.content | b64decode)"
        fail_msg: "Log file does not contain expected update message"
        success_msg: "Log file contains expected update message"
        
    - name: Check package facts were gathered
      ansible.builtin.assert:
        that:
          - ansible_facts.packages is defined
        fail_msg: "Package facts were not gathered"
        success_msg: "Package facts were successfully gathered"