---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: "Include install_cert_manager role"
      ansible.builtin.include_role:
        name: install_cert_manager