---
# - name: Deploy Docmost using Kubernetes collection
#   kubernetes.core.k8s:
#     state: present
#     definition: "{{ lookup('kubernetes.core.kustomize', dir=k8s_docmost_path) }}"
#     wait: yes
#     wait_timeout: 300
#   register: docmost_deploy_result
#   changed_when: docmost_deploy_result.changed
#   ignore_errors: no  # Fail if deployment fails

- name: Deploy Docmost Definitions
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
  with_fileglob:
    - "docmost/*.yaml"