---
# - name: Deploy Ghost using Kubernetes collection
#   kubernetes.core.k8s:
#     state: present
#     definition: "{{ lookup('kubernetes.core.kustomize', dir=k8s_ghost_path) }}"
#     wait: yes
#     wait_timeout: 300
#   register: ghost_deploy_result
#   changed_when: ghost_deploy_result.changed
#   ignore_errors: no  # Fail if deployment fails

- name: Deploy Ghost Definitions
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
  with_fileglob:
    - "ghost/*.yaml"
