---
# This role has been split into separate application-specific roles:
# - install_k8s_dashboard: For Kubernetes Dashboard
# - install_kubeseal: For Sealed Secrets
# - install_ghost: For Ghost blogging platform  
# - install_docmost: For Docmost documentation platform
#
# Use the individual roles instead of this one