---
- name: notify success
  include_tasks: ../tasks/main.yml
  vars:
    ntfy_message: "{{ ntfy_success_message | default('Operation completed successfully') }}"
    ntfy_title: "{{ ntfy_success_title | default('Success') }}"
    ntfy_priority: "{{ ntfy_success_priority | default('default') }}"
    ntfy_tags: "{{ ntfy_success_tags | default('white_check_mark') }}"

- name: notify failure
  include_tasks: ../tasks/main.yml
  vars:
    ntfy_message: "{{ ntfy_failure_message | default('Operation failed') }}"
    ntfy_title: "{{ ntfy_failure_title | default('Failure') }}"
    ntfy_priority: "{{ ntfy_failure_priority | default('urgent') }}"
    ntfy_tags: "{{ ntfy_failure_tags | default('x,warning') }}"

- name: notify warning
  include_tasks: ../tasks/main.yml
  vars:
    ntfy_message: "{{ ntfy_warning_message | default('Warning condition detected') }}"
    ntfy_title: "{{ ntfy_warning_title | default('Warning') }}"
    ntfy_priority: "{{ ntfy_warning_priority | default('high') }}"
    ntfy_tags: "{{ ntfy_warning_tags | default('warning,exclamation') }}"

- name: notify deployment
  include_tasks: ../tasks/main.yml
  vars:
    ntfy_message: "{{ ntfy_deployment_message | default('Deployment completed') }}"
    ntfy_title: "{{ ntfy_deployment_title | default('Deployment') }}"
    ntfy_priority: "{{ ntfy_deployment_priority | default('default') }}"
    ntfy_tags: "{{ ntfy_deployment_tags | default('rocket,white_check_mark') }}" 