---
galaxy_info:
  role_name: system_update
  author: Your Name
  description: Role to update system packages across different Linux distributions
  company: Your Company (optional)
  license: MIT
  min_ansible_version: 2.9
  
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
    - name: EL
      versions:
        - 7
        - 8
        - 9
    - name: Fedora
      versions:
        - 35
        - 36
        - 37
        - 38
    - name: Archlinux
      versions:
        - all
    - name: opensuse
      versions:
        - all

  galaxy_tags:
    - system
    - packages
    - updates
    - security
    - maintenance

dependencies: [] 