---
- name: Reboot device
  ansible.builtin.reboot:
    msg: "Rebooting device"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  become: true
