---
- name: Send ntfy notification
  ansible.builtin.uri:
    url: "{{ ntfy_server }}/{{ ntfy_topic }}"
    method: POST
    body: "{{ ntfy_message }}"
    headers:
      Content-Type: "text/plain"
      Title: "{{ ntfy_title | default(omit) }}"
      Priority: "{{ ntfy_priority | default(omit) }}"
      Tags: "{{ ntfy_tags | default(omit) }}"
      Click: "{{ ntfy_click_url | default(omit) }}"
      Attach: "{{ ntfy_attach_url | default(omit) }}"
      Actions: "{{ ntfy_actions | default(omit) }}"
      Email: "{{ ntfy_email | default(omit) }}"
      X-Delay: "{{ ntfy_delay | default(omit) }}"
      X-Markdown: "{{ ntfy_markdown | default(omit) }}"
      X-Icon: "{{ ntfy_icon | default(omit) }}"
      Authorization: "{{ ntfy_auth | default(omit) }}"
    status_code: 200
    timeout: 30
  register: ntfy_result
  when: ntfy_message is defined and ntfy_topic is defined

- name: Display ntfy notification result
  ansible.builtin.debug:
    msg: "Notification sent successfully to topic '{{ ntfy_topic }}'"
  when: ntfy_result is succeeded and ntfy_debug | default(false)

- name: Handle ntfy notification failure
  ansible.builtin.fail:
    msg: "Failed to send ntfy notification: {{ ntfy_result.msg | default('Unknown error') }}"
  when: ntfy_result is failed and ntfy_fail_on_error | default(true) 