---
dependency:
  name: galaxy
driver:
  name: delegated
platforms: []
provisioner:
  name: ansible
scenario:
  test_sequence:
    - syntax
    - verify
verifier:
  name: ansible
  playbooks:
    verify: verify.yml