---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    # Ensure Python and temporary directory are available
    - name: Ensure Python and required system packages are installed
      ansible.builtin.raw: |
        test -e /usr/bin/python3 || (apt -y update && apt install -y python3 python3-apt)
        mkdir -p /root/.ansible/tmp
        chmod 700 /root/.ansible/tmp
      changed_when: false

    # The geerlingguy image already has systemd and python installed
    # Just make sure we have the specific packages needed for the role
    - name: Ensure required packages are installed
      ansible.builtin.apt:
        name:
          - procps
        state: present
        
    # Create the /boot/firmware directory structure for testing
    - name: Create /boot directory if it doesn't exist
      ansible.builtin.file:
        path: /boot
        state: directory
        mode: '0755'
      ignore_errors: true
        
    - name: Create /boot/firmware directory
      ansible.builtin.file:
        path: /boot/firmware
        state: directory
        mode: '0755'
      ignore_errors: true
        
    # Create a mock cmdline.txt file with typical Raspberry Pi content
    - name: Create mock cmdline.txt file
      ansible.builtin.copy:
        dest: /boot/firmware/cmdline.txt
        content: "console=serial0,115200 console=tty1 root=PARTUUID=738a4d67-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait"
        mode: '0644'
      ignore_errors: true 