---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Verify open-iscsi package is installed
      ansible.builtin.package_facts:
        manager: auto
    
    - name: Assert open-iscsi is installed
      ansible.builtin.assert:
        that: "'open-iscsi' in ansible_facts.packages"
        fail_msg: "open-iscsi package is not installed"
        success_msg: "open-iscsi package is installed correctly"
        
    - name: Verify iscsid service is running
      ansible.builtin.service_facts:
      
    - name: Assert iscsid service is running and enabled
      ansible.builtin.assert:
        that:
          - "ansible_facts.services['iscsid.service'] is defined"
          - "ansible_facts.services['iscsid.service'].state == 'running'"
          - "ansible_facts.services['iscsid.service'].status == 'enabled'"
        fail_msg: "iscsid service is not running or enabled"
        success_msg: "iscsid service is running and enabled correctly"
        
    - name: Verify cmdline.txt has cgroup parameters
      ansible.builtin.command: cat /boot/firmware/cmdline.txt
      register: cmdline_content
      changed_when: false
      
    - name: Assert cmdline.txt has cgroup parameters
      ansible.builtin.assert:
        that: 
          - "'cgroup_memory=1' in cmdline_content.stdout"
          - "'cgroup_enable=memory' in cmdline_content.stdout"
        fail_msg: "cmdline.txt does not have required cgroup parameters"
        success_msg: "cmdline.txt has required cgroup parameters"
    # Additional verification tasks can be added based on what your role does
    # For example, checking if services are running, files exist, configurations are set, etc.
    - name: Print test summary
      debug:
        msg: "ALL TESTS PASSED SUCCESSFULLY!"
      when: true
