---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghost-mysql
  namespace: ghost
spec:
  encryptedData:
    password: AgB1OuW4QDrckiJCGUaR/DH9gqwboaXKWcyutn9A8B1TmD5YHs7ClKNlGsB0ObbXXYFhYTcj9gQoTdshQYeH2hBa0iVxxLB6sSD+gKH99mQ4JaqBXjjBrp1eBPVdroiYRBEtCk8OzPLtQ0jfdbCqd0APjQ+7fNqcrNWe23JjlfScKe3oKRVjVgVoOlEB2T/dx9164RdMOGKZZRQWpQV6cYYrcZtOt2GMAA4GfzSUHiurAfJ0E8dFej/dvyYqnyTcbsZ/RSO/xdeIiycZyHNZ7W2nXE55Fcv7kMtxSib6MfBaYYgSBtrYJyNwpx1sUOeiL3QbTrvD9UKELE/V84X4zMwGuowCP5pOy1lUQn4pZrAd3EaR7JhhBzxD7daN6WO3S7Qe+mGJLsNBN0EvCAilAABw4FxeOHTDq5bb0otpAlYcHagtYC6/T1S2U7gIcisyoOK+JvbgySjem25wXoEqsOni6Yg15BcaDtGa8PnvybR1XQJ3efeZCUMfmirR2XjZeO/+sM65lGy1x3k6YMFjph+HhF5Ep48hIkisF4e+lWC+UJ2GANcfKPvhb8J7VhtuFoV9vieGCgZMacfnDcHZAnvvJ9PttdFDb7aXB5vi2PgL7MMYNma7MwAxEDIkkXbvde8iIe0TAvYrybxc70KkLyqmMLMNiPQFRq5VtzCvJd0e2tAb43hqFKHYK2WxaaSzvfZ/OqxqcQy/Gl2CoSZDnDnKOWOLbw==
  template:
    metadata:
      creationTimestamp: null
      name: ghost-mysql
      namespace: ghost
    type: Opaque
