apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: docmost
  namespace: docmost
spec:
  serviceName: docmost
  replicas: 1
  selector:
    matchLabels:
      app: docmost
  template:
    metadata:
      labels:
        app: docmost
    spec:
      containers:
        - name: docmost
          image: docmost/docmost:latest
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  name: docmost-config
                  key: APP_URL
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: docmost-secrets
                  key: APP_SECRET
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: docmost-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: docmost-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: docmost-data
              mountPath: /app/data/storage
  volumeClaimTemplates:
    - metadata:
        name: docmost-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: docmost
  namespace: docmost
spec:
  selector:
    app: docmost
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  type: LoadBalancer 