apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docmost-storage
  namespace: docmost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage
  namespace: docmost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-storage
  namespace: docmost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 