---
- name: Setup nix environment
  hosts: localhost
  gather_facts: false
  # vars_prompt:
  # - name: prompt_token
  #   prompt: "Enter your Cloudflare API token"
  #   private: true
  #   default: ""
  roles:
    - lix
    - nix_darwin
    # - dns_cname

- name: Setup raspberry pis
  hosts: raspberrypi
  gather_facts: false
  roles:
    - rpi_setup

- name: Setup k8s (includes dashboard, docmost, and ghost)
  hosts: localhost
  gather_facts: false
  roles:
    - k8s