---
- name: Setup nix environment
  hosts: localhost
  gather_facts: false
  roles:
    - lix
    - nix_darwin

- name: Setup raspberry pis
  hosts: raspberrypi
  gather_facts: false
  roles:
    - rpi_setup

- name: Setup k8s (includes dashboard, docmost, and ghost)
  hosts: localhost
  gather_facts: false
  roles:
    - k8s