---
- name: Test ntfy notification role
  hosts: localhost
  connection: local
  gather_facts: true
  
  vars:
    ntfy_topic: "ee4ccfad-efdb-4862-8f38-d7455bcbd198"
    ntfy_auth: "{{ lookup('env', 'NTFY_AUTH') | default('') }}"
  
  tasks:
    - name: Send basic notification
      include_role:
        name: ntfy_notify
      vars:
        ntfy_message: "Hello from Ansible! This is a basic test message."
        ntfy_debug: true

    - name: Send advanced notification with multiple features
      include_role:
        name: ntfy_notify
      vars:
        ntfy_message: |
          **Ansible Playbook Execution**
          
          This notification includes:
          - Markdown formatting
          - High priority
          - Custom tags
          - Click action
          
          System: {{ ansible_hostname }}
          Date: {{ ansible_date_time.iso8601 }}
        ntfy_title: "Ansible Test Complete"
        ntfy_priority: "high"
        ntfy_tags: "ansible,white_check_mark,computer"
        ntfy_markdown: true
        ntfy_click_url: "https://docs.ansible.com"
        ntfy_debug: true

    - name: Send notification with email
      include_role:
        name: ntfy_notify
      vars:
        ntfy_message: "This notification will also be sent via email if you have email configured for the topic."
        ntfy_title: "Email Notification Test"
        ntfy_priority: "default"
        ntfy_tags: "email,information_source"
        # Uncomment the line below and add your email to test email notifications
        # ntfy_email: "your-email@example.com"
        ntfy_debug: true

    - name: Send delayed notification (10 seconds)
      include_role:
        name: ntfy_notify
      vars:
        ntfy_message: "This message was delayed by 10 seconds!"
        ntfy_title: "Delayed Message"
        ntfy_delay: "10s"
        ntfy_tags: "hourglass_flowing_sand,clock"
        ntfy_debug: true

    - name: Send notification with action button
      include_role:
        name: ntfy_notify
      vars:
        ntfy_message: "Click the button below to visit the Ansible documentation."
        ntfy_title: "Action Button Test"
        ntfy_actions: "view, Visit Docs, https://docs.ansible.com"
        ntfy_tags: "book,link"
        ntfy_debug: true

    - name: Show completion message
      debug:
        msg: |
          All test notifications have been sent!
          
          To receive these notifications:
          1. Install the ntfy app on your phone
          2. Subscribe to the topic 'ee4ccfad-efdb-4862-8f38-d7455bcbd198'
          3. Or visit https://ntfy.sh/ee4ccfad-efdb-4862-8f38-d7455bcbd198 in your browser
          
          Note: The delayed notification will arrive in 10 seconds. 