---
# NFS Persistent Volume for media
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: media
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: ansible
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  nfs:
    server: 172.16.10.248
    path: /volume2/media
---
# PVC for NFS media
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: media
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: ansible
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media
  resources:
    requests:
      storage: 1Ti
---
# PVC for config/metadata (local storage)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: media
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: ansible
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi 